version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: payment
      MYSQL_DATABASE: payment
      MYSQL_USER: payment
      MYSQL_PASSWORD: payment
    ports:
    - "3306:3306"