application:
  env: ${ENV:development}
  name: '@pom.name@'
  description: '@pom.description@'
  version: '@pom.version@'

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/payment?useSSL=false"
    username: ${DATASOURCE_USERNAME:payment}
    password: ${DATASOURCE_PASSWORD:payment}
    hikari:
      minimumIdle: ${HIKARI_MINIMUM_IDLE:10}
      maximumPoolSize: ${HIKARI_MAXIMUM_POLL_SIZE:10}

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  flyway:
    check-location: true
    enabled: true
    url: jdbc:mysql://127.0.0.1:3306/payment?useSSL=false
    user: ${DATASOURCE_USERNAME:payment}
    password: ${DATASOURCE_PASSWORD:payment}

  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false

  security:   
    basic:
      enabled: false

  main:
    allow-bean-definition-overriding: true

jwt:
  secretKey: ${JWT_SECRET_KEY:stubJWT}

server:
   port: ${PORT:8080}

sentry:
  dsn: ${SENTRY}
