CREATE TABLE reason (
  id MEDIUMINT AUTO_INCREMENT NOT NULL,
  created_at DATETIME NOT NULL,
  description VARCHAR(45) NOT NULL,
  enable TINYINT(1) NOT NULL,
  name VARCHAR(45) NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT UK_REASON_NAME UNIQUE (name)
);